language: python

matrix:
  include:
    - python: "2.7"
      install:
        - pip install flake8
        - pip install pytest
        - pip install ./html5lib
        - pip install pytest-travis-fold
        - pip install typing
      script:
        - py.test lint manifest
        - flake8

    - python: "3.5"
      install:
        - pip install flake8
        - pip install pytest
        - pip install ./html5lib
        - pip install pytest-travis-fold
        - pip install typing
      script:
        - py.test lint manifest
        - flake8

    - python: "3.5"
      install:
        - pip install mypy-lang
        - pip install typing
      script:
        - mypy lint/lint.py
        - mypy --py2 lint/lint.py
